-- 为已有库补全表/字段注释（幂等：重复执行仅更新 COMMENT，不改变列类型）
USE lingyi_doc_db;

-- users
ALTER TABLE users
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '主键 UUID',
  MODIFY COLUMN email VARCHAR(255) NOT NULL COMMENT '登录邮箱，唯一',
  MODIFY COLUMN password_hash VARCHAR(255) NOT NULL COMMENT 'bcrypt 密码哈希',
  MODIFY COLUMN display_name VARCHAR(100) NOT NULL COMMENT '显示昵称',
  MODIFY COLUMN avatar_url VARCHAR(500) DEFAULT NULL COMMENT '头像 URL',
  MODIFY COLUMN phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  MODIFY COLUMN locale VARCHAR(10) DEFAULT 'zh-CN' COMMENT '界面语言',
  MODIFY COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=启用 0=禁用',
  MODIFY COLUMN last_login_at TIMESTAMP NULL DEFAULT NULL COMMENT '最近登录时间',
  MODIFY COLUMN login_fail_count TINYINT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
  MODIFY COLUMN locked_until TIMESTAMP NULL DEFAULT NULL COMMENT '账号锁定截止时间',
  MODIFY COLUMN oauth_union_id VARCHAR(128) DEFAULT NULL COMMENT '云端 OAuth UnionId，私有化 NULL',
  MODIFY COLUMN ldap_uuid VARCHAR(128) DEFAULT NULL COMMENT 'LDAP UUID，预留',
  MODIFY COLUMN personal_setting JSON DEFAULT NULL COMMENT '个人全局配置 JSON';

-- documents
ALTER TABLE documents
  MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT '文档 ID，如 doc_xxx',
  MODIFY COLUMN title VARCHAR(500) NOT NULL COMMENT '文档标题',
  MODIFY COLUMN description TEXT DEFAULT NULL COMMENT '文档描述',
  MODIFY COLUMN doc_type VARCHAR(20) NOT NULL DEFAULT 'freeform' COMMENT 'richtext|freeform|base|mindnote|slides|whiteboard',
  MODIFY COLUMN owner_id CHAR(36) DEFAULT NULL COMMENT '个人文档所有者 users.id',
  MODIFY COLUMN tenant_id CHAR(36) DEFAULT NULL COMMENT '企业文档所属租户 tenants.id',
  MODIFY COLUMN org_id CHAR(36) DEFAULT NULL COMMENT '归属组织 organizations.id',
  MODIFY COLUMN current_version INT NOT NULL DEFAULT 0 COMMENT '当前内容版本号',
  MODIFY COLUMN content_json JSON DEFAULT NULL COMMENT '文档内容 JSON 快照',
  MODIFY COLUMN storage_size BIGINT NOT NULL DEFAULT 0 COMMENT '内容占用字节数',
  MODIFY COLUMN last_snapshot_version INT NOT NULL DEFAULT 0 COMMENT '最近快照版本号',
  MODIFY COLUMN last_snapshot_at TIMESTAMP NULL DEFAULT NULL COMMENT '最近快照时间',
  MODIFY COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=已软删除',
  MODIFY COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL COMMENT '软删除时间',
  MODIFY COLUMN last_visited_at TIMESTAMP NULL DEFAULT NULL COMMENT '用户最近访问时间';

-- tenants
ALTER TABLE tenants
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '主键 UUID',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '企业/团队名称',
  MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '0=禁用 1=正常',
  MODIFY COLUMN admin_user_id CHAR(36) DEFAULT NULL COMMENT '租户超级管理员 users.id',
  MODIFY COLUMN deploy_type TINYINT NOT NULL DEFAULT 1 COMMENT '1=SaaS 2=本地私有化 3=专属私有化',
  MODIFY COLUMN is_physical_isolate TINYINT NOT NULL DEFAULT 0 COMMENT '1=物理隔离部署',
  MODIFY COLUMN account_mode TINYINT NOT NULL DEFAULT 1 COMMENT '1=云端账号 2=本地离线账号',
  MODIFY COLUMN is_allow_multi_switch TINYINT NOT NULL DEFAULT 1 COMMENT '1=允许多身份切换',
  MODIFY COLUMN db_instance_id VARCHAR(64) DEFAULT NULL COMMENT '专属库实例标识',
  MODIFY COLUMN storage_cluster_id VARCHAR(64) DEFAULT NULL COMMENT '专属存储集群标识',
  MODIFY COLUMN private_config JSON DEFAULT NULL COMMENT '私有化扩展配置';

-- quota_daily_log
ALTER TABLE quota_daily_log
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN log_date DATE NOT NULL COMMENT '统计日期',
  MODIFY COLUMN count_value INT NOT NULL DEFAULT 0 COMMENT '当日累计次数',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

INSERT IGNORE INTO schema_migrations (version) VALUES ('20260706_column_comments');
