export default () => ({
  db: {
    host: process.env.DB_HOST || '127.0.0.1',
    port: Number(process.env.DB_PORT || 3306),
    username: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'lingyi_doc_db',
    connectionLimit: Number(process.env.DB_CONN_LIMIT || 10),
  },
  jwt: {
    secret: process.env.JWT_SECRET || 'dev-secret-change-in-production',
    consumerAccessTtl: Number(process.env.JWT_CONSUMER_ACCESS_TTL || 7200),
    consumerRefreshTtl: Number(process.env.JWT_CONSUMER_REFRESH_TTL || 2592000),
    adminAccessTtl: Number(process.env.JWT_ADMIN_ACCESS_TTL || 1800),
    adminRefreshTtl: Number(process.env.JWT_ADMIN_REFRESH_TTL || 604800),
  },
  auth: {
    rsaPrivateKeyB64: process.env.AUTH_RSA_PRIVATE_KEY_B64 || '',
    /** HTTP 等非安全上下文无法使用 Web Crypto 时，允许明文密码（仅 dev 建议开启） */
    allowPlainPassword: process.env.AUTH_PASSWORD_ALLOW_PLAIN === '1',
  },
  deploy: {
    type: Number(process.env.DEPLOY_TYPE || 1),
    accountMode: Number(process.env.ACCOUNT_MODE || 1),
    defaultTenantId: process.env.DEFAULT_TENANT_ID || '',
    defaultTenantName: process.env.DEFAULT_TENANT_NAME || '默认企业',
    allowMultiTenantSwitch: process.env.ALLOW_MULTI_TENANT_SWITCH !== '0',
    enforceTenantFilter: process.env.ENFORCE_TENANT_FILTER !== '0',
  },
  api: {
    port: Number(process.env.API_PORT || 3000),
    corsOrigin: process.env.CORS_ORIGIN || '*',
  },
  oss: {
    enabled: process.env.OSS_ENABLED !== '0',
    region: process.env.OSS_REGION || 'cn-hangzhou',
    bucket: process.env.OSS_BUCKET || '',
    endpoint: process.env.OSS_ENDPOINT || 'oss-cn-hangzhou.aliyuncs.com',
    accessKeyId: process.env.OSS_ACCESS_KEY_ID || '',
    accessKeySecret: process.env.OSS_ACCESS_KEY_SECRET || '',
    publicBaseUrl: process.env.OSS_PUBLIC_BASE_URL || '',
    prefix: process.env.OSS_PREFIX || 'dev',
    objectAcl: process.env.OSS_OBJECT_ACL || '',
    accessMode: (process.env.OSS_ACCESS_MODE || 'private') as 'private' | 'public',
    accessUrlTtl: Number(process.env.OSS_ACCESS_URL_TTL || 10 * 365 * 24 * 3600),
    accessSignSecret: process.env.OSS_ACCESS_SIGN_SECRET || '',
  },
  sms: {
    mock: process.env.SMS_MOCK === '1',
    endpoint: process.env.ALIYUN_SMS_ENDPOINT || 'dypnsapi.aliyuncs.com',
    accessKeyId: process.env.ALIYUN_SMS_ACCESS_KEY_ID || process.env.OSS_ACCESS_KEY_ID || '',
    accessKeySecret: process.env.ALIYUN_SMS_ACCESS_KEY_SECRET || process.env.OSS_ACCESS_KEY_SECRET || '',
    signName: process.env.ALIYUN_SMS_SIGN_NAME || '速通互联验证码',
    templateCode: process.env.ALIYUN_SMS_TEMPLATE_CODE || '100001',
    sendIntervalSec: Number(process.env.SMS_SEND_INTERVAL_SEC || 60),
    codeTtlMinutes: Number(process.env.SMS_CODE_TTL_MINUTES || 5),
    verifiedTtlMinutes: Number(process.env.SMS_VERIFIED_TTL_MINUTES || 10),
    phoneMaxPerDay: Number(process.env.SMS_PHONE_MAX_PER_DAY || 10),
    ipMaxPerHour: Number(process.env.SMS_IP_MAX_PER_HOUR || 20),
    verifyMaxFails: Number(process.env.SMS_VERIFY_MAX_FAILS || 5),
  },
  rateLimit: {
    loginIpMaxPerHour: Number(process.env.LOGIN_IP_MAX_PER_HOUR || 60),
    loginAccountMaxPerHour: Number(process.env.LOGIN_ACCOUNT_MAX_PER_HOUR || 30),
  },
  log: {
    level: process.env.LOG_LEVEL || 'log',
    json: process.env.LOG_JSON === '1' || process.env.NODE_ENV === 'production',
    http: process.env.LOG_HTTP !== '0',
    slowRequestMs: Number(process.env.LOG_SLOW_REQUEST_MS || 1000),
  },
  redis: {
    url: process.env.REDIS_URL || 'redis://127.0.0.1:6379',
    keyPrefix: process.env.REDIS_KEY_PREFIX || 'lingyi_doc:',
    connectTimeoutMs: Number(process.env.REDIS_CONNECT_TIMEOUT_MS || 5000),
  },
  collab: {
    enabled: process.env.FEATURE_COLLAB_ENABLED === 'true',
    wsPath: process.env.WS_PATH || '/api/v1/collab/ws',
    roomMaxUsers: Number(process.env.COLLAB_ROOM_MAX_USERS || 50),
    heartbeatIntervalMs: Number(process.env.COLLAB_HEARTBEAT_INTERVAL_MS || 30000),
    presenceTtlSec: Number(process.env.COLLAB_PRESENCE_TTL_SEC || 90),
    opsPerSecondLimit: Number(process.env.COLLAB_OPS_PER_SECOND_LIMIT || 100),
  },
  comments: {
    enabled: process.env.FEATURE_COMMENTS_ENABLED === 'true',
  },
});
